name: Deploy to Vercel

on:
  pull_request:
    branches:
      - '**'
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            vercel --prod --yes --token=$VERCEL_TOKEN
          else
            vercel --yes --token=$VERCEL_TOKEN
          fi
